class AppStrings {
  static String currentLang = 'EN';

  // دالة جلب الترجمة
  static String tr(String key) {
    return _localizedValues[currentLang]?[key] ?? key;
  }

  // دالة تبديل اللغة
  static void toggleLang() {
    currentLang = currentLang == 'EN' ? 'AR' : 'EN';
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'EN': {
      'synced': 'SYNCED',
      'offline': 'OFFLINE',
      'live_hud': 'LIVE HUD',
      'real_time_stats': 'Real-time Stats Grid',
      'processes': 'PROCESSES',
      'grouped_kill': 'Grouped Kill Manager',
      'ai_optimizer': 'AI OPTIMIZER',
      'neural_core': 'Neural Game Core',
      'alerts_config': 'ALERTS CONFIG',
      'vib_thresh': 'Vibration Thresholds',
      'session_overview': 'SESSION OVERVIEW',
      'runtime': 'Runtime',
      'max_cpu': 'Max CPU',
      'max_gpu': 'Max GPU',
      'avg_fps': 'Avg FPS',
      'net_ping': 'Net Ping',
      'vram_alloc': 'VRAM Alloc',
      'silent_mode': 'SILENT',
      'game_mode': 'GAME',
      'overclock_mode': 'OVERCLOCK',
      'mode_suffix': 'MODE',
      'fps_core': 'FPS CORE',
      'pulse': 'PULSE',
      'optimal': 'OPTIMAL',
      'high_load': 'HIGH LOAD',
      'overheating': 'OVERHEATING',
      'cpu_core': 'CPU CORE',
      'gpu_core': 'GPU CORE',
      'ram_alloc': 'RAM ALLOC',
      'raw_telemetry': 'RAW TELEMETRY MATRIX',
      'cpu_pwr': 'CPU PWR',
      'gpu_pwr': 'GPU PWR',
      'cpu_clk': 'CPU CLK',
      'cpu_fan': 'CPU FAN',
      'gpu_fan': 'GPU FAN',
      'mobo': 'MOBO',
      'disk': 'DISK',
      'hyper_clean': '🧹 HYPER CLEAN',
      'bg_clean_complete': 'Background clean complete!',
      'kill_all': 'KILL ALL',
      'security_thresh': 'SECURITY THRESHOLDS',
      'cpu_temp_limit': 'CPU Temp Limit (Alarm)',
      'gpu_temp_limit': 'GPU Temp Limit (Alarm)',
      'max_ping_limit': 'Max Ping Limit',
      'min_fps_limit': 'Min FPS Limit',
      'system_logs': 'SYSTEM LOGS',
      'warning_thermal': '> WARNING: THERMAL PROTECTION ENGAGED!',
      'system_clean_logs':
          '> Systems running clean.\n> Waiting for anomalies...',
      'neural_offline': 'NEURAL ENGINE OFFLINE',
      'ai_requires_token':
          'AI Game Optimizer requires Cloud Token.\nWAN Subscription feature incoming.',
      'self_destruct': 'SELF DESTRUCT',
      'kill_warning':
          'Are you sure you want to kill the RigPulse PC Agent?\n\nBackground process will stop immediately.',
      'cancel': 'CANCEL',
      'kill_agent': 'KILL AGENT',
      'live_fps': 'LIVE FPS',
    },
    'AR': {
      'synced': 'متصل',
      'offline': 'غير متصل',
      'live_hud': 'المراقبة الحية',
      'real_time_stats': 'إحصائيات الوقت الفعلي',
      'processes': 'العمليات',
      'grouped_kill': 'إدارة وتجميع المهام',
      'ai_optimizer': 'الذكاء الاصطناعي',
      'neural_core': 'محرك الألعاب العصبي',
      'alerts_config': 'إعدادات الإنذار',
      'vib_thresh': 'التحكم في الاهتزاز والحرارة',
      'session_overview': 'ملخص الجلسة',
      'runtime': 'مدة التشغيل',
      'max_cpu': 'أقصى حرارة معالج',
      'max_gpu': 'أقصى حرارة كارت',
      'avg_fps': 'متوسط الفريمات',
      'net_ping': 'البنغ',
      'vram_alloc': 'استهلاك VRAM',
      'silent_mode': 'هادئ',
      'game_mode': 'ألعاب',
      'overclock_mode': 'أداء فائق',
      'mode_suffix': 'وضع',
      'fps_core': 'معدل الإطارات',
      'pulse': 'حالة النبض',
      'optimal': 'أداء مثالي',
      'high_load': 'ضغط مرتفع',
      'overheating': 'حرارة حرجة',
      'cpu_core': 'نواة المعالج',
      'gpu_core': 'نواة الكارت',
      'ram_alloc': 'استهلاك الرام',
      'raw_telemetry': 'مصفوفة البيانات الخام',
      'cpu_pwr': 'طاقة المعالج',
      'gpu_pwr': 'طاقة الكارت',
      'cpu_clk': 'تردد المعالج',
      'cpu_fan': 'مروحة المعالج',
      'gpu_fan': 'مروحة الكارت',
      'mobo': 'اللوحة الأم',
      'disk': 'القرص',
      'hyper_clean': '🧹 تنظيف عميق',
      'bg_clean_complete': 'تم تنظيف الخلفية بنجاح!',
      'kill_all': 'إنهاء الكل',
      'security_thresh': 'حدود الأمان (الإنذارات)',
      'cpu_temp_limit': 'حد حرارة المعالج',
      'gpu_temp_limit': 'حد حرارة الكارت',
      'max_ping_limit': 'الحد الأقصى للبنغ',
      'min_fps_limit': 'الحد الأدنى للفريمات',
      'system_logs': 'سجلات النظام',
      'warning_thermal': '> تحذير: تم تفعيل الحماية الحرارية!',
      'system_clean_logs': '> النظام يعمل بأمان.\n> في انتظار أي شذوذ...',
      'neural_offline': 'المحرك العصبي غير متصل',
      'ai_requires_token':
          'يتطلب الذكاء الاصطناعي اشتراك سحابي.\nالميزة قادمة قريباً.',
      'self_destruct': 'التدمير الذاتي',
      'kill_warning':
          'هل أنت متأكد من قتل سيرفر RigPulse؟\n\nستتوقف العملية في الخلفية فوراً وتُفصل عن الهاتف.',
      'cancel': 'إلغاء',
      'kill_agent': 'إغلاق السيرفر',
      'live_fps': 'الفريمات',
    }
  };
}
